name: Deploy to Hugging Face

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Hugging Face auth
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pip install -U huggingface_hub
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git config --global credential.helper store
          hf auth login --token "$HF_TOKEN" --add-to-git-credential

      - name: Push to Hugging Face Space
        run: |
          git clone https://huggingface.co/spaces/tanvitiwari2004/sentinel8 hf-space

          rm -rf hf-space/dashboard hf-space/data hf-space/models

          cp -r dashboard hf-space/dashboard
          cp -r data hf-space/data
          cp -r models hf-space/models

          cp requirements.txt hf-space/requirements.txt
          cp Dockerfile hf-space/Dockerfile

          cd hf-space
          git add .
          git commit -m "sync from GitHub" || echo "nothing to commit"
          git push